# -*- coding: utf-8 -*-
"""Portfolio_Final_CLEAN copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVFkGXRwvqDkNwVJnwQ_elTfT-cMGMhn

# OPIM 5641 — Final Project: Portfolio Optimization Project
**Author:** Zarina Owens

---

## What this notebook does

I have **$1000** to invest. I want to spread it across 10 stocks chosen from a pool of 20 (2 per sector), and rebalance over time. The question: **which strategy makes the most money without destroying me on a bad day?**

I tested 5 different approaches and compared them against just buying SPY (S&P 500 ETF — 'buy and hold').

### The 5 strategies
| # | Name | Idea in one sentence | Source |
|---|------|----------------------|--------|
| 1 | **MINLP (Pyomo + Bonmin)** | Mixed-integer program: pick 10 of 20, optimize Sharpe, **5-day sliding window** | Prof. Wanik / Womack lecture notebook |
| 2 | **EWMA + Ledoit-Wolf** | Smart return forecast + shrunk covariance | quant industry standard |
| 3 | **HRP** | Cluster stocks, distribute risk down a tree | López de Prado (2016), JPMorgan, AQR |
| 4 | **Black-Litterman** | Start from market equilibrium, layer on my views | Goldman Sachs (1990) |
| 5 | **Fama-French 5-factor** | Predict returns from 5 academic factors | Eugene Fama (Nobel Prize 2013) |

## Step 1. Install libraries
- `yfinance` — free stock prices from Yahoo Finance
- `scikit-learn` — Ledoit-Wolf covariance shrinkage
- `pandas-datareader` — Fama-French factors
- `pyomo` + **Bonmin** — for the MINLP in Method 1 (same solver as Prof. Wanik's lecture notebook)
"""

!pip install yfinance scikit-learn pandas-datareader pyomo idaes-pse -q

# Bonmin solver via IDAES (most reliable in Colab)
import os, subprocess
subprocess.run(['idaes', 'get-extensions', '--to', './bin'], check=False)
BONMIN_PATH = os.path.abspath('./bin/bonmin')
if not os.path.exists(BONMIN_PATH):
    # Fallback: try AMPL binary
    subprocess.run(['wget', '-q', 'https://ampl.com/dl/open/bonmin/bonmin-linux64.zip'], check=False)
    subprocess.run(['unzip', '-q', '-o', 'bonmin-linux64.zip'], check=False)
    BONMIN_PATH = os.path.abspath('./bonmin')
if os.path.exists(BONMIN_PATH):
    os.chmod(BONMIN_PATH, 0o755)
    print(f'✅ Bonmin installed at: {BONMIN_PATH}')
else:
    BONMIN_PATH = None
    print('⚠️  Bonmin install failed — Method 1 will use scipy fallback (still satisfies linking constraints)')

import warnings, time
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.cluster.hierarchy import linkage
from scipy.spatial.distance import squareform
from sklearn.covariance import LedoitWolf
from pyomo.environ import (ConcreteModel, Var, Binary, NonNegativeReals,
                            Constraint, Objective, maximize, SolverFactory, value)
from pyomo.environ import sqrt as pyo_sqrt

STARTING_CAPITAL = 1000.0
TRANSACTION_COST = 0.001     # 0.1% per trade — typical for Robinhood/IBKR

STOCK_POOL = {
    'Tech':        ['AAPL', 'MSFT', 'NVDA', 'GOOGL'],
    'Healthcare':  ['JNJ', 'PFE', 'UNH', 'LLY'],
    'Utilities':   ['NEE', 'DUK', 'SO', 'AEP'],
    'Commodities': ['XOM', 'CVX', 'NEM', 'FCX'],
    'Finance':     ['JPM', 'BAC', 'GS', 'V'],
}
TICKERS = [t for s in STOCK_POOL.values() for t in s]
plt.rcParams['figure.figsize'] = (13, 6)
print(f'Ready. Tickers: {len(TICKERS)}, sectors: {len(STOCK_POOL)}')

"""## Step 2. Load data
5 years of daily prices — covers COVID-2020, 2022 bear, 2023-2024 AI boom.

Also load Fama-French 5 factors from Kenneth French's website (used in Method 5).
"""

print('Downloading 5 years of data...')
data = yf.download(TICKERS + ['SPY'], period='5y',
                   interval='1d', auto_adjust=True, progress=False)['Close'].dropna()
returns = data[TICKERS + ['SPY']].pct_change().dropna()
print(f'Got {len(returns)} trading days')
print(f'Period: {returns.index[0].date()}  →  {returns.index[-1].date()}')

try:
    from pandas_datareader.famafrench import FamaFrenchReader
    ff5 = FamaFrenchReader('F-F_Research_Data_5_Factors_2x3_daily',
                          start=returns.index[0], end=returns.index[-1]).read()[0] / 100
    ff5.index = pd.to_datetime(ff5.index)
    ff5 = ff5.reindex(returns.index).fillna(method='ffill')
    print(f'Fama-French factors loaded: {ff5.columns.tolist()}')
except Exception as e:
    print(f'⚠️ FF5 failed to load ({e}). Method 5 will be skipped.')
    ff5 = None

"""## Step 3. Backtest engine
Each day: strategy → weights → 0.1% commission on turnover → daily return → log.

If a strategy returns `None` on a given day (e.g. Method 1 only re-optimizes every 5 days), we **hold the previous weights** rather than skipping the day.

Metrics: **Sharpe** (>1 ok, >2 great), **Sortino** (only penalizes losses), **Drawdown** (worst peak-to-trough loss).
"""

def run_backtest(weights_func, name, start_idx=60):
    portfolio_value = STARTING_CAPITAL
    prev_weights = None
    log = []
    for i in range(start_idx, len(returns)):
        new_weights = weights_func(i)
        if new_weights is None:
            if prev_weights is None: continue
            weights = prev_weights
            turnover = 0.0
        else:
            weights = new_weights
            if prev_weights is not None:
                turnover = sum(abs(weights.get(t, 0) - prev_weights.get(t, 0)) for t in TICKERS)
            else:
                turnover = sum(weights.get(t, 0) for t in TICKERS)
        portfolio_value -= portfolio_value * turnover * TRANSACTION_COST
        today = returns[TICKERS].iloc[i]
        port_ret = sum(weights.get(t, 0) * today[t] for t in TICKERS)
        portfolio_value *= (1 + port_ret)
        log.append({'date': returns.index[i], 'value': portfolio_value, 'daily_return': port_ret})
        prev_weights = weights
    return pd.DataFrame(log).set_index('date')

def metrics(df, name):
    r = df['daily_return']
    final = df['value'].iloc[-1]
    sharpe = (r.mean() / r.std()) * np.sqrt(252) if r.std() > 0 else 0
    downside = r[r < 0]
    sortino = (r.mean() / downside.std()) * np.sqrt(252) if len(downside) and downside.std() > 0 else 0
    dd = ((df['value'] - df['value'].cummax()) / df['value'].cummax()).min() * 100
    return {'Method': name, 'Final ($)': round(final, 2),
            'Return (%)': round((final/STARTING_CAPITAL - 1)*100, 1),
            'Sharpe': round(sharpe, 2), 'Sortino': round(sortino, 2),
            'Drawdown (%)': round(dd, 1)}

def select_10(mu, cov_mat):
    """Helper for Methods 2, 4, 5: pick top in each sector + top-5 by Sharpe."""
    sharpe = mu / np.sqrt(np.diag(cov_mat))
    selected = set()
    for sector_tix in STOCK_POOL.values():
        idx = [TICKERS.index(t) for t in sector_tix]
        selected.add(idx[np.argmax(sharpe[idx])])
    rem = sorted([k for k in range(len(TICKERS)) if k not in selected], key=lambda k: -sharpe[k])
    while len(selected) < 10 and rem: selected.add(rem.pop(0))
    return sorted(selected)

print('Engine ready ✅')

"""## Method 1 — MINLP with Pyomo + Bonmin (Prof. Wanik / Womack approach)

**This is the original formulation from the lecture notebook.** Mixed-Integer Nonlinear Program (MINLP).

"""

def solve_minlp(mu, cov, n_select=10, w_min=0.05, w_max=0.30):
    """Womack-style MINLP via Pyomo + Bonmin. Falls back to scipy + greedy selection if Bonmin unavailable."""
    n = len(mu)
    if BONMIN_PATH is None:
        # Scipy fallback: continuous QP, then greedy round to 10 with linking constraints
        return _scipy_minlp_fallback(mu, cov, n_select, w_min, w_max)
    m = ConcreteModel()
    m.I = range(n)
    m.y = Var(m.I, domain=Binary)
    m.x = Var(m.I, domain=NonNegativeReals, bounds=(0, w_max))
    m.sum_x = Constraint(expr=sum(m.x[i] for i in m.I) == 1)
    m.sum_y = Constraint(expr=sum(m.y[i] for i in m.I) == n_select)
    m.link_lo = Constraint(m.I, rule=lambda m, i: m.x[i] >= w_min * m.y[i])
    m.link_hi = Constraint(m.I, rule=lambda m, i: m.x[i] <= w_max * m.y[i])
    sector_constraints = []
    for sector, tix in STOCK_POOL.items():
        idx = [TICKERS.index(t) for t in tix]
        sector_constraints.append(sum(m.y[i] for i in idx) >= 1)
    m.sector_min = Constraint(range(len(sector_constraints)),
                              rule=lambda m, k: sector_constraints[k])
    def sharpe_obj(m):
        ret = sum(mu[i] * m.x[i] for i in m.I)
        var = sum(cov[i, j] * m.x[i] * m.x[j] for i in m.I for j in m.I)
        return ret / pyo_sqrt(var + 1e-10)
    m.obj = Objective(rule=sharpe_obj, sense=maximize)
    solver = SolverFactory('bonmin', executable=BONMIN_PATH)
    try:
        solver.solve(m, tee=False)
        return np.array([value(m.x[i]) for i in m.I])
    except Exception:
        return _scipy_minlp_fallback(mu, cov, n_select, w_min, w_max)

def _scipy_minlp_fallback(mu, cov, n_select=10, w_min=0.05, w_max=0.30):
    """Approximate MINLP: pick top stocks by Sharpe (1 per sector + top by Sharpe), then continuous QP."""
    selected = select_10(mu, cov)
    sub_mu = mu[selected]; sub_cov = cov[np.ix_(selected, selected)]
    res = minimize(lambda w: -((w@sub_mu) / np.sqrt(w@sub_cov@w + 1e-10)),
                   np.ones(n_select)/n_select, method='SLSQP',
                   bounds=[(w_min, w_max)]*n_select,
                   constraints=[{'type':'eq','fun':lambda w: w.sum()-1}])
    if not res.success: return None
    x = np.zeros(len(mu))
    for idx, val in zip(selected, res.x): x[idx] = val
    return x

WINDOW = 5
REBALANCE_EVERY = 5
_method1_cache = {'weights': None, 'last_idx': -100}

def method1_weights(i):
    if i < WINDOW: return None
    if i - _method1_cache['last_idx'] < REBALANCE_EVERY and _method1_cache['weights'] is not None:
        return None
    history = returns[TICKERS].iloc[i-WINDOW:i]
    mu = history.mean().values
    cov = history.cov().values
    x = solve_minlp(mu, cov)
    if x is None: return None
    w = pd.Series(x, index=TICKERS).to_dict()
    _method1_cache['weights'] = w
    _method1_cache['last_idx'] = i
    return w
print('Method 1 (MINLP, 5-day window) ✅')

"""## Method 2 — EWMA + Ledoit-Wolf
**EWMA** = recent days weigh more. **Momentum 12-1** = Jegadeesh-Titman (1993) academic factor. **Ledoit-Wolf shrinkage** = stable covariance on small samples. **SLSQP** = scipy continuous optimizer.
"""

def method2_weights(i):
    if i < 273: return None
    history = returns[TICKERS].iloc[max(0, i-252):i]
    cov_history = returns[TICKERS].iloc[i-60:i]
    ewma = history.ewm(halflife=20).mean().iloc[-1]
    momentum = history.iloc[-252:-21].sum() / 252
    mu = (0.5*ewma + 0.5*momentum)[TICKERS].values
    lw = LedoitWolf(); lw.fit(cov_history.values); cov_mat = lw.covariance_
    selected = select_10(mu, cov_mat)
    sub_mu = mu[selected]; sub_cov = cov_mat[np.ix_(selected, selected)]
    res = minimize(lambda w: -(w@sub_mu - 2.5*0.5*w@sub_cov@w), np.ones(10)/10,
                   method='SLSQP', bounds=[(0.05, 0.30)]*10,
                   constraints=[{'type':'eq','fun':lambda w: w.sum()-1}])
    if not res.success: return None
    w = pd.Series(0.0, index=TICKERS)
    for idx, val in zip(selected, res.x): w[TICKERS[idx]] = val
    return w.to_dict()
print('Method 2 ✅')

"""## Method 3 — Hierarchical Risk Parity (HRP)

**Why HRP:** classical optimizers invert the covariance matrix — unstable on small samples. HRP avoids inversion entirely:
1. Compute correlations → distances
2. Build cluster tree (single-linkage)
3. Allocate risk by recursive bisection

Source: López de Prado, *JoPM 2016*. Used at JPMorgan, AQR, Two Sigma.
"""

def hrp_weights_from_cov(cov):
    std = np.sqrt(np.diag(cov))
    corr = np.clip(cov / np.outer(std, std), -1, 1)
    np.fill_diagonal(corr, 1.0)
    dist = np.sqrt(0.5 * (1 - corr))
    link = linkage(squareform(dist, checks=False), method='single')
    def get_quasi_diag(link):
        link = link.astype(int)
        sort_ix = pd.Series([link[-1, 0], link[-1, 1]])
        n_items = link[-1, 3]
        while sort_ix.max() >= n_items:
            sort_ix.index = range(0, sort_ix.shape[0]*2, 2)
            df0 = sort_ix[sort_ix >= n_items]
            i = df0.index; j = df0.values - n_items
            sort_ix[i] = link[j, 0]
            df0 = pd.Series(link[j, 1], index=i+1)
            sort_ix = pd.concat([sort_ix, df0]).sort_index()
        return sort_ix.tolist()
    sort_ix = get_quasi_diag(link)
    w = pd.Series(1.0, index=sort_ix)
    clusters = [sort_ix]
    while len(clusters) > 0:
        clusters = [c[s:e] for c in clusters
                    for s, e in ((0, len(c)//2), (len(c)//2, len(c))) if len(c) > 1]
        for i in range(0, len(clusters), 2):
            c0, c1 = clusters[i], clusters[i+1]
            def cluster_var(c):
                sub = cov[np.ix_(c, c)]
                ivp = 1.0 / np.diag(sub); ivp /= ivp.sum()
                return ivp @ sub @ ivp
            v0, v1 = cluster_var(c0), cluster_var(c1)
            alpha = 1 - v0 / (v0 + v1)
            w[c0] *= alpha; w[c1] *= (1 - alpha)
    return w.sort_index()

def method3_weights(i):
    if i < 60: return None
    cov_history = returns[TICKERS].iloc[i-60:i]
    lw = LedoitWolf(); lw.fit(cov_history.values); cov_mat = lw.covariance_
    try:
        w_arr = hrp_weights_from_cov(cov_mat).values
    except Exception:
        return None
    w_arr = np.clip(w_arr, 0.02, 0.30); w_arr /= w_arr.sum()
    return dict(zip(TICKERS, w_arr))
print('Method 3 (HRP) ✅')

"""## Method 4 — Black-Litterman (Goldman Sachs, 1990)

Start from market equilibrium (what prices imply), overlay views with proper uncertainty weighting.
Result: Method 2-style weights but **much more stable**.
"""

def method4_weights(i):
    if i < 273: return None
    history = returns[TICKERS].iloc[max(0, i-252):i]
    cov_history = returns[TICKERS].iloc[i-60:i]
    lw = LedoitWolf(); lw.fit(cov_history.values); Sigma = lw.covariance_
    n = len(TICKERS)
    w_market = np.ones(n) / n
    delta = 2.5
    pi = delta * Sigma @ w_market
    momentum = (history.iloc[-252:-21].sum() / 252).values
    ewma = history.ewm(halflife=20).mean().iloc[-1].values
    Q = 0.5 * momentum + 0.5 * ewma
    P = np.eye(n)
    tau = 0.05
    Omega = np.diag(np.diag(P @ (tau * Sigma) @ P.T))
    inv_tau_sigma = np.linalg.inv(tau * Sigma)
    inv_omega = np.linalg.inv(Omega + 1e-8 * np.eye(n))
    A = inv_tau_sigma + P.T @ inv_omega @ P
    b = inv_tau_sigma @ pi + P.T @ inv_omega @ Q
    mu_bl = np.linalg.solve(A, b)
    selected = select_10(mu_bl, Sigma)
    sub_mu = mu_bl[selected]; sub_cov = Sigma[np.ix_(selected, selected)]
    res = minimize(lambda w: -(w@sub_mu - delta*0.5*w@sub_cov@w), np.ones(10)/10,
                   method='SLSQP', bounds=[(0.05, 0.30)]*10,
                   constraints=[{'type':'eq','fun':lambda w: w.sum()-1}])
    if not res.success: return None
    w = pd.Series(0.0, index=TICKERS)
    for idx, val in zip(selected, res.x): w[TICKERS[idx]] = val
    return w.to_dict()
print('Method 4 (Black-Litterman) ✅')

"""## Method 5 — Fama-French 5-factor model

Eugene Fama's Nobel-Prize work (2013).
"""

def method5_weights(i):
    if ff5 is None: return None
    if i < 273: return None
    history = returns[TICKERS].iloc[max(0, i-252):i]
    factors = ff5.iloc[max(0, i-252):i]
    if len(factors) < 200: return None
    cov_history = returns[TICKERS].iloc[i-60:i]
    lw = LedoitWolf(); lw.fit(cov_history.values); cov_mat = lw.covariance_
    F = factors[['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA']].values
    F_mean = F.mean(axis=0)
    F_design = np.column_stack([np.ones(len(F)), F])
    mu = np.zeros(len(TICKERS))
    for k, t in enumerate(TICKERS):
        y = history[t].values - factors['RF'].values
        beta, _, _, _ = np.linalg.lstsq(F_design, y, rcond=None)
        mu[k] = beta[0] + beta[1:] @ F_mean + factors['RF'].mean()
    selected = select_10(mu, cov_mat)
    sub_mu = mu[selected]; sub_cov = cov_mat[np.ix_(selected, selected)]
    res = minimize(lambda w: -(w@sub_mu - 2.5*0.5*w@sub_cov@w), np.ones(10)/10,
                   method='SLSQP', bounds=[(0.05, 0.30)]*10,
                   constraints=[{'type':'eq','fun':lambda w: w.sum()-1}])
    if not res.success: return None
    w = pd.Series(0.0, index=TICKERS)
    for idx, val in zip(selected, res.x): w[TICKERS[idx]] = val
    return w.to_dict()
print('Method 5 (Fama-French) ✅')

"""## Step 4. Run all methods (with timing)
Method 1 (MINLP) is the slowest
"""

timings = {}
_method1_cache.update({'weights': None, 'last_idx': -100})
print('Running all methods...\n')

t0 = time.time(); m1 = run_backtest(method1_weights, 'Method 1', start_idx=WINDOW)
timings['Method 1 (MINLP)'] = time.time() - t0; print(f'  Method 1 done in {timings["Method 1 (MINLP)"]:.1f}s')

t0 = time.time(); m2 = run_backtest(method2_weights, 'Method 2', start_idx=273)
timings['Method 2 (EWMA+LW)'] = time.time() - t0; print(f'  Method 2 done in {timings["Method 2 (EWMA+LW)"]:.1f}s')

t0 = time.time(); m3 = run_backtest(method3_weights, 'Method 3', start_idx=60)
timings['Method 3 (HRP)'] = time.time() - t0; print(f'  Method 3 done in {timings["Method 3 (HRP)"]:.1f}s')

t0 = time.time(); m4 = run_backtest(method4_weights, 'Method 4', start_idx=273)
timings['Method 4 (Black-Litterman)'] = time.time() - t0; print(f'  Method 4 done in {timings["Method 4 (Black-Litterman)"]:.1f}s')

if ff5 is not None:
    t0 = time.time(); m5 = run_backtest(method5_weights, 'Method 5', start_idx=273)
    timings['Method 5 (Fama-French)'] = time.time() - t0; print(f'  Method 5 done in {timings["Method 5 (Fama-French)"]:.1f}s')
else:
    m5 = None

spy = pd.DataFrame({
    'value': STARTING_CAPITAL * (1 + returns['SPY']).cumprod(),
    'daily_return': returns['SPY']
}).iloc[5:]

print('\n⏱️  Timing summary:')
for name, t in timings.items():
    print(f'  {name:30s}  {t:6.1f} sec')

"""## Step 5. Results table"""

rows = [
    metrics(m1, 'Method 1 (MINLP/Bonmin)'),
    metrics(m2, 'Method 2 (EWMA+LW)'),
    metrics(m3, 'Method 3 (HRP)'),
    metrics(m4, 'Method 4 (Black-Litterman)'),
]
if m5 is not None: rows.append(metrics(m5, 'Method 5 (Fama-French)'))
rows.append(metrics(spy, 'SPY (buy & hold)'))
results = pd.DataFrame(rows)
print('=' * 70)
print('RESULTS OVER 5 YEARS — growth of $1000')
print('=' * 70)
results

"""## Step 6. Equity curves"""

colors = {
    'Method 1 (MINLP/Bonmin)':    '#999999',
    'Method 2 (EWMA+LW)':         '#5A7A6A',
    'Method 3 (HRP)':             '#0B6E4F',
    'Method 4 (Black-Litterman)': '#7B2CBF',
    'Method 5 (Fama-French)':     '#F77F00',
    'SPY (buy & hold)':           '#1B2A4E',
}
plot_data = [(m1, 'Method 1 (MINLP/Bonmin)'), (m2, 'Method 2 (EWMA+LW)'),
             (m3, 'Method 3 (HRP)'), (m4, 'Method 4 (Black-Litterman)')]
if m5 is not None: plot_data.append((m5, 'Method 5 (Fama-French)'))
plot_data.append((spy, 'SPY (buy & hold)'))
fig, ax = plt.subplots(figsize=(13, 7))
for df, name in plot_data:
    lw = 3 if 'SPY' in name else 1.8
    ax.plot(df.index, df['value'], label=name, color=colors[name], lw=lw)
ax.axhline(STARTING_CAPITAL, color='gray', ls='--', alpha=0.4)
ax.set_ylabel('Portfolio value ($)')
ax.set_title('5 methods + SPY over 5 years (incl. COVID-2020 and 2022 bear)')
ax.legend(loc='upper left', fontsize=10)
ax.grid(alpha=0.3)
plt.show()

"""## Step 7. Walk-Forward Analysis
Split 5 years into 3 non-overlapping periods. A method is good only if it works in **all three**.
"""

n = len(returns)
thirds = [returns.index[n//3], returns.index[2*n//3], returns.index[-1]]
starts = [returns.index[0], thirds[0], thirds[1]]
ends = thirds
period_names = [f'Period {i+1}\n{starts[i].date()} →\n{ends[i].date()}' for i in range(3)]

def period_sharpe(df, p_start, p_end):
    sub = df.loc[p_start:p_end]
    if len(sub) < 20: return np.nan
    r = sub['daily_return']
    return (r.mean() / r.std()) * np.sqrt(252) if r.std() > 0 else 0

wf_pairs = [(m1, 'Method 1 (MINLP/Bonmin)'), (m2, 'Method 2 (EWMA+LW)'),
            (m3, 'Method 3 (HRP)'), (m4, 'Method 4 (Black-Litterman)')]
if m5 is not None: wf_pairs.append((m5, 'Method 5 (Fama-French)'))
wf_pairs.append((spy, 'SPY (buy & hold)'))
wf_data = []
for df, name in wf_pairs:
    row = {'Method': name}
    for i, (s, e) in enumerate(zip(starts, ends)):
        row[f'Period {i+1}'] = round(period_sharpe(df, s, e), 2)
    wf_data.append(row)
wf_df = pd.DataFrame(wf_data)
wf_df['Mean'] = wf_df[[f'Period {i+1}' for i in range(3)]].mean(axis=1).round(2)
wf_df['Std'] = wf_df[[f'Period {i+1}' for i in range(3)]].std(axis=1).round(2)
wf_df['Stability'] = (wf_df['Mean'] / (wf_df['Std'].abs() + 1e-9)).round(2)
wf_df

fig, ax = plt.subplots(figsize=(11, 5))
wf_matrix = wf_df.set_index('Method')[[f'Period {i+1}' for i in range(3)]].values
im = ax.imshow(wf_matrix, cmap='RdYlGn', aspect='auto', vmin=-1, vmax=3)
ax.set_xticks(range(3)); ax.set_xticklabels(period_names, fontsize=9)
ax.set_yticks(range(len(wf_df))); ax.set_yticklabels(wf_df['Method'])
for i in range(len(wf_df)):
    for j in range(3):
        v = wf_matrix[i, j]
        ax.text(j, i, f'{v:.2f}', ha='center', va='center',
                color='white' if abs(v) > 1.5 else 'black', fontweight='bold')
plt.colorbar(im, label='Sharpe Ratio')
plt.title('Walk-Forward Sharpe — who works in DIFFERENT market regimes?')
plt.tight_layout(); plt.show()

"""## Step 8. Final ranking
**Score = 40% × Sharpe + 30% × Stability + 30% × Drawdown protection**
"""

final = results.merge(wf_df[['Method', 'Stability']], on='Method', how='left')
final['Score'] = (
    0.4 * (final['Sharpe'] / final['Sharpe'].max())
    + 0.3 * (final['Stability'].fillna(0) / (final['Stability'].abs().max() + 1e-9))
    + 0.3 * (1 - final['Drawdown (%)'] / final['Drawdown (%)'].min())
).round(3)
final = final.sort_values('Score', ascending=False).reset_index(drop=True)
print('FINAL RANKING:')
final[['Method', 'Final ($)', 'Sharpe', 'Drawdown (%)', 'Stability', 'Score']]